spring.application.name=Dev-Learning-Roadmap-Manager

server.port=8081

# ============================================
# BASE DE DONNEES PRODUCTION
# ============================================
# Remplace par les vraies credentials de ton serveur de production
spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:54317/railway
spring.datasource.username=postgres
spring.datasource.password=IPczqQMJgIoMUToefQlqOiwKAGEfjRNr

# ============================================
# JPA/HIBERNATE PRODUCTION
# ============================================
# IMPORTANT : "validate" en prod (jamais update ou create)
# validate = vérifie que le schéma DB correspond aux entités sans modifier
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# STOCKAGE FICHIERS
# ============================================
# Chemin absolu sur le serveur de production
file.upload-dir=/var/app/uploads

# ============================================
# UPLOAD
# ============================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ============================================
# JACKSON
# ============================================
spring.jackson.serialization.write-dates-as-timestamps=false

# ============================================
# JWT
# ============================================
# Durée : 24h
jwt.expiration.time=86400000
# Utilise une clé différente et plus forte en production
jwt.secret.key=aGVsbG8td29ybGQtc2VjcmV0LWtleS1mb3ItcHJvZHVjdGlvbi11c2Utb25seS1kb25vdC1zaGFyZS10aGlzLWtleS0yMDI2LWVkdWNhdGlvbnByaW9yaXRl

# ============================================
# JAVA MAIL SENDER GMAIL
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=educationpriorites@gmail.com
spring.mail.password=hlnq kart mjjq uzhg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000

# ============================================
# LOGS PRODUCTION
# ============================================
# Réduit les logs en production pour les performances
logging.level.root=WARN
logging.level.com.devpro=INFO
logging.level.org.hibernate.SQL=OFF